name: First Test
on: push
jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello World!"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          cache: 'gradle'
          java-version: '17'
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Last step
        run: echo "End of workflow!"